# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd210a19bdea5c8fbf196a0c3b2138db73655499ae8ca7c9c5770eddc0dda1506b1211e65bb2972eca54f13752474301c6bb96080bb94a4a547de6b0e76ddced

test:
  secret_key_base: bd0932d263d477ac0eb492c8875db05381b64d5b0d4acabd0daf887379f0fd914aa5b302a773a29a7064b3a7c701895b5d8c546841514d2b8ddc1d491e497c92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
